// @flow

export const CHATS_FETCH_REQUESTED = 'CHATS_FETCH_REQUESTED';
export const PUT_CHATS = 'PUT_CHATS';
export const SET_CHATS_FETCH_FAILED_ERROR_MESSAGE = 'SET_CHATS_FETCH_FAILED_ERROR_MESSAGE';

export const MESSAGES_FETCH_REQUESTED = 'MESSAGES_FETCH_REQUESTED';
export const PUT_CHAT_MESSAGES = 'PUT_CHAT_MESSAGES';
export const SET_MESSAGES_FETCH_FAILED_ERROR_MESSAGE = 'SET_MESSAGES_FETCH_FAILED_ERROR_MESSAGE';
