// @flow

// home actions
export const USERS_FETCH_REQUESTED = 'USERS_FETCH_REQUESTED';
export const PUT_USERS = 'PUT_USERS';
export const SET_USERS_FETCH_FAILED_ERROR_MESSAGE = 'SET_USERS_FETCH_FAILED_ERROR_MESSAGE';
export const CREATE_CHAT_REQUESTED = 'CREATE_CHAT_REQUESTED';
export const ADD_NEW_CHAT = 'ADD_NEW_CHAT';
export const CHATS_FETCH_REQUESTED = 'CHATS_FETCH_REQUESTED';
export const PUT_CHATS = 'PUT_CHATS';
export const SET_CHATS_FETCH_FAILED_ERROR_MESSAGE = 'SET_CHATS_FETCH_FAILED_ERROR_MESSAGE';
export const UPDATE_CHAT_LAST_MESSAGE = 'UPDATE_CHAT_LAST_MESSAGE';

// chat actions
export const MESSAGES_FETCH_REQUESTED = 'MESSAGES_FETCH_REQUESTED';
export const PUT_CHAT_MESSAGES = 'PUT_CHAT_MESSAGES';
export const SET_MESSAGES_FETCH_FAILED_ERROR_MESSAGE = 'SET_MESSAGES_FETCH_FAILED_ERROR_MESSAGE';
export const RECIEVE_CHAT_MESSAGE = 'RECIEVE_CHAT_MESSAGE';

// main actions
export const GET_AUTHENTICATED_USER = 'GET_AUTHENTICATED_USER';
export const PUT_AUTHENTICATED_USER = 'PUT_AUTHENTICATED_USER';
export const SET_AUTHENTICATED_USER_FETCH_FAILED_ERROR_MESSAGE = 'SET_AUTHENTICATED_USER_FETCH_FAILED_ERROR_MESSAGE';
