export const CHATS_FETCH_REQUESTED = 'CHATS_FETCH_REQUESTED';
export const CHATS_FETCH_SUCCEEDED = 'CHATS_FETCH_SUCCEEDED';
export const CHATS_FETCH_FAILED = 'CHATS_FETCH_FAILED';

export const MESSAGES_FETCH_REQUESTED = 'MESSAGES_FETCH_REQUEST';
export const MESSAGES_FETCH_SUCCEEDED = 'MESSAGES_FETCH_SUCCEEDED';
export const MESSAGES_FETCH_FAILED = 'MESSAGES_FETCH_FAILED';
