export const SEND_MESSAGE = 'SEND_MESSAGE';
export const READ_MESSAGE = 'READ_MESSAGE';
export const DISPLAY_CHAT_ON_RECIPIENT_SIDE = 'DISPLAY_CHAT_ON_RECIPIENT_SIDE';

export const CHAT_NEW = 'CHAT_NEW';
export const CHAT_ALREADY_EXISTS = 'CHAT_ALREADY_EXISTS';
